### PR TITLE
Prepare for general consumption

### PR DESCRIPTION
**Pull request by panglesd**
This:
- simplifies the structure (by hiding files, mostly)
- rewrites the README to guide more
- provide solutions!

### CODE REVIEW

**Comment by lyrm** [comment]
Thanks ! I only had the time for a quick look but it is looking great !

One point though, I was initially planning to order the exercise like the lecture : 
- no scheduler (so `Saturn` and `Domain` only),
- then do the part of the lecture on `Eio`
- then with `Eio.Domain_manager` and/or `Eio.Executor_pool`

But it seems you have find an other way around. Could you explain to me what you have in mind ?

**Comment by panglesd** [comment]
So, I tried to do the exercises with only domains. But it was not working... (my attempt are still present in the git history of the solutions). If I remember correctly, I had some unhandled effects.

Instead of blaming my solutions, I decided this is because the `Actor` library uses `Eio`. And (maybe) you cannot call some `Eio` managed functions from within a `Domain` you created yourself, as they don't inherit effect handlers?

Maybe that is still possible to use domains only for computing the image, but only send the recomposed image from the domain managed by `Eio`? Or maybe we should have a "domain-compatible" version of the `Actor` library?

**Comment by lyrm** [comment]
My mistake, sorry. You need a bit of Eio to handle the client part, absolutely. What I said (and I am sorry I was unclear) is only for the computation part :) 

The `naive` implementation is the minimum one:

```ocaml
let username = Sys.argv.(1)
let uri = try Some Sys.argv.(2) with _ -> None

let () =
  Eio_main.run @@ fun env ->
  let client = Actor.client ?uri ~username env in
  while true do
    let sub = Actor.request client in
    let img = Actor.render sub in
    Actor.respond client img
  done
```

Hope this clarify my remark :) also if you think this is better in this way (help with a scheduler and than without a already-defined scheduler) I am happy to discuss it.

**Comment by panglesd** [comment]
So, if I understand correctly, your suggestion is to add a section for:
> Parallelize the computation of the image. Use `Actor.{h;v}split` to split the jobs, and `Actor.join` to merge the computed images. /!\ Do not call `Actor.request/Actor.respond` from within a newly created domain! /!\

?

**Pull request merged**
